spring:
  application:
    name: resilience4j-example
  profiles:
    include:
      - circuitbreaker
      - retry
  main:
    banner-mode: off

management:
  info:
    env:
      enabled: true
  endpoints:
    web.exposure.include: '*'
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

logging:
  level:
    by.svyat: DEBUG
